// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NumberManagmentAPI;

namespace NumberManagmentAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220627021145_InitiallCreate")]
    partial class InitiallCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY_DESCRIPTION");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<DateTime>("DhCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_CREATED");

                    b.Property<DateTime>("DhUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_UPDATED");

                    b.HasKey("CategoryId");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("App.Models.EquipamentModel", b =>
                {
                    b.Property<int>("EquipamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EQUIPAMENT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DhCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_CREATED");

                    b.Property<DateTime>("DhUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_UPDATED");

                    b.Property<string>("EquipamentDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("EquipamentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("EquipamentId");

                    b.ToTable("EQUIPAMENT");
                });

            modelBuilder.Entity("App.Models.NumberEquipamentModel", b =>
                {
                    b.Property<int>("EquipamentId")
                        .HasColumnType("int")
                        .HasColumnName("ID_EQUIPAMENT");

                    b.Property<int>("NumberId")
                        .HasColumnType("int")
                        .HasColumnName("ID_NUMBER");

                    b.Property<DateTime>("DhCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_CREATED");

                    b.Property<DateTime>("DhUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_UPDATED");

                    b.HasKey("EquipamentId", "NumberId");

                    b.HasIndex("NumberId");

                    b.ToTable("NUMBER_EQUIPAMENT");
                });

            modelBuilder.Entity("App.Models.NumberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_NUMBER")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Ddd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DDD");

                    b.Property<DateTime>("DhCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_CREATED");

                    b.Property<DateTime>("DhUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_UPDATED");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PREFIX");

                    b.Property<string>("Sufix")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUFIX");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("NUMBER");
                });

            modelBuilder.Entity("App.Models.NumberStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_NUMBER_STATUS")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NUMBER_STATUS_NAME");

                    b.HasKey("Id");

                    b.ToTable("NUMBER_STATUS");
                });

            modelBuilder.Entity("App.Models.QuarentineInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DhCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_CREATED");

                    b.Property<DateTime>("DhUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DH_UPDATED");

                    b.Property<string>("FullNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FULL_NUMBER");

                    b.Property<string>("QauntityDays")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QUANTITY_DAYS");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("TxtDesciptionJob")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT_DESCRIPTION_JOB");

                    b.Property<string>("UserUpdate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_UPDATE");

                    b.HasKey("Id");

                    b.ToTable("QUARENTINE");
                });

            modelBuilder.Entity("App.Models.NumberEquipamentModel", b =>
                {
                    b.HasOne("App.Models.EquipamentModel", "Equipament")
                        .WithMany()
                        .HasForeignKey("EquipamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.NumberModel", "Number")
                        .WithMany()
                        .HasForeignKey("NumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipament");

                    b.Navigation("Number");
                });

            modelBuilder.Entity("App.Models.NumberModel", b =>
                {
                    b.HasOne("App.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
